#
#  .swiftlint.yml
#  Honzapda
#
#  Created by YOUJIM on 2/26/24.
#


disabled_rules:
  - colon
  - force_cast
  - identifier_name
  - force_unwrapping
  - line_length

opt_in_rules:
  - empty_count
  - empty_string
  
included: # 린트 과정에 포함할 파일 경로. 이 항목이 존재하면 `--path`는 무시됨

excluded: # 린트 과정에서 무시할 파일 경로. `included`보다 우선순위 높음
  - Pods
  - Honzapda/Application/HonzapdaApp.swift

# 한 줄의 최대 길이를 99로 설정합니다.
line_length:
  warning: 99

# 빈 줄의 최대 연속 개수를 1로 설정합니다.
vertical_whitespace:
  max_empty_lines: 1

# 콜론(:) 오른쪽에 공백을 두지 않도록 설정합니다.
colon:
  apply_to_parameters: false
  apply_to_function_declaration: true
  apply_to_function_call: true

# 강제 타입 캐스팅을 경고 수준으로 설정합니다.
force_cast:
  severity: warning

# 식별자 이름의 최소 길이를 3, 최대 길이를 20으로 설정하고 허용되는 기호를 지정합니다.
identifier_name:
  min_length:
    error: 3
  max_length:
    warning: 15
    error: 20
  allowed_symbols: "_"
  excluded:
    - id
    - URL
    - HTML
    - URLString
    - CGFloatLiteral
    - SwiftyColor
    - get

# 강제 언래핑을 경고 수준으로 설정합니다.
force_unwrapping:
  severity: warning

# 복잡성 측정을 위한 순환 복잡성 경고 수준을 10으로 설정합니다.
cyclomatic_complexity:
  warning: 10

# 중첩된 if-else 문 수준을 3으로 설정합니다.
nesting:
  type: "if_else"
  levels: 3

# 함수의 파라미터 개수 경고 수준을 6으로 설정합니다.
function_parameter_count:
  warning: 6

# 빈 줄 뒤의 공백을 무시하도록 설정합니다.
trailing_whitespace:
  ignoring_empty_lines: true

# 빈 줄 앞의 공백을 무시하도록 설정합니다.
leading_whitespace:
  ignore_empty_lines: true

custom_rules:
  # 모듈 임포트를 알파벳 순으로 정렬하고 내장 프레임워크를 먼저, 빈 줄로 구분하여 서드파티 프레임워크를 임포트합니다.
  - pattern: "import (.*)"
    severity: warning
    regex: true
    message: "Imports should be sorted alphabetically. Core frameworks should be imported first, followed by third-party frameworks. Empty line should separate different groups of imports."

  # MARK 구문 위와 아래에는 공백을 추가합니다.
  - pattern: "^\s*// MARK:.*$"
    severity: warning
  - pattern: "^.*// MARK:.*\n[^\n]"
    severity: warning
    
  # 클래스와 구조체의 이름에는 UpperCamelCase를 사용하고, 클래스 이름에 접두사를 붙이지 않습니다.
  - pattern: "class\s+Prefix[A-Z]"
    regex: true
    severity: error
    message: "Class names should use UpperCamelCase and should not have prefixes."
  - pattern: "struct\s+Prefix[A-Z]"
    regex: true
    severity: error
    message: "Struct names should use UpperCamelCase and should not have prefixes."
    
  # 열거형(enum)는 lowerCamelCase를 사용합니다.
  - pattern: "[ ]{1,}case\s+[A-Z].*"
    severity: error
    message: "Enum cases should use lowerCamelCase."

